### ISSUE TITLE
Update Chat sample to work with latest orbit version(1.4.1) on windows.

### ISSUE THREAD

**Issue by i3oi3o** [orbit/orbit-samples#2]
I test on window platfrom with 
- orbit version 1.4.1
- orbit-hk2 version 0.9.4
- orbit-jetty version 0.9.3
- maven.compiler.source 1.8
- maven.compiler.target 1.8

Somehow, it cannot discover cluster on windows. Probably, this is something about Jgroup config.
The log from Jgroup 

> ก.ย. 26, 2560 6:04:02 หลังเที่ยง org.infinispan.util.logging.events.impl.BasicEventLogger log
> INFO: ISPN100000: Node orbit-chat-sample joined the cluster
> ก.ย. 26, 2560 6:04:02 หลังเที่ยง org.infinispan.topology.ClusterTopologyManagerImpl handleClusterView
> ERROR: ISPN000421: Error while handling view 1
> java.lang.NoSuchMethodError: org.infinispan.util.logging.Log.debugf(Ljava/lang/String;I)V
>         at org.infinispan.topology.ClusterTopologyManagerImpl.recoverClusterStatus(ClusterTopologyManagerImpl.java:475)
>         at org.infinispan.topology.ClusterTopologyManagerImpl.becomeCoordinator(ClusterTopologyManagerImpl.java:359)
>         at org.infinispan.topology.ClusterTopologyManagerImpl.handleClusterView(ClusterTopologyManagerImpl.java:338)
>         at org.infinispan.topology.ClusterTopologyManagerImpl.access$500(ClusterTopologyManagerImpl.java:83)
>         at org.infinispan.topology.ClusterTopologyManagerImpl$ClusterViewListener.lambda$handleViewChange$0(ClusterTopologyManagerImpl.java:765)
>         at org.infinispan.executors.LimitedExecutor.runTasks(LimitedExecutor.java:144)
>         at org.infinispan.executors.LimitedExecutor.access$100(LimitedExecutor.java:33)
>         at org.infinispan.executors.LimitedExecutor$Runner.run(LimitedExecutor.java:174)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>         at java.lang.Thread.run(Thread.java:748)

If I use orbit version 0.9.9, everything works fine. Did I do something wrong?

**Comment by JoeHegarty** [comment]
Thanks, this is probably just an incompatibility between versions we need to fix.
The samples actually use things like orbit-hk2 etc that we don't recommend anymore so they could do with a cleanup.
I'll take a look at fixing this up, but the Hello World guide might be helpful in the meantime as it details how to get running without any other libraries: https://github.com/orbit/orbit/wiki/Getting-Started%3A-Hello-World
